---
name: Fey
version: 0.21
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Better SQL Generation Through Perl
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey
  homepage: http://www.fey-project.org/
  license: http://dev.perl.org/licenses/
  repository: http://hg.urth.org/hg/Fey
requires:
  Exception::Class: 0
  Exporter: 0
  List::AllUtils: 0
  Moose: 0.66
  MooseX::AttributeHelpers: 0.13
  MooseX::Params::Validate: 0.08
  MooseX::SemiAffordanceAccessor: 0.03
  MooseX::StrictConstructor: 0.07
  Scalar::Util: 0
  Task::Weaken: 0.99
build_requires:
  DBI: 0
  Fey::Test: 0.05
  File::Temp: 0
  Test::MockObject: 0
  Test::More: 0
recommends:
  Test::Memory::Cycle: 0
provides:
  Fey:
    file: lib/Fey.pm
    version: 0.21
  Fey::Column:
    file: lib/Fey/Column.pm
  Fey::Column::Alias:
    file: lib/Fey/Column/Alias.pm
  Fey::Exceptions:
    file: lib/Fey/Exceptions.pm
  Fey::FK:
    file: lib/Fey/FK.pm
  Fey::FakeDBI:
    file: lib/Fey/FakeDBI.pm
  Fey::Literal:
    file: lib/Fey/Literal.pm
  Fey::Literal::Function:
    file: lib/Fey/Literal/Function.pm
  Fey::Literal::Null:
    file: lib/Fey/Literal/Null.pm
  Fey::Literal::Number:
    file: lib/Fey/Literal/Number.pm
  Fey::Literal::String:
    file: lib/Fey/Literal/String.pm
  Fey::Literal::Term:
    file: lib/Fey/Literal/Term.pm
  Fey::NamedObjectSet:
    file: lib/Fey/NamedObjectSet.pm
  Fey::Placeholder:
    file: lib/Fey/Placeholder.pm
  Fey::Role::ColumnLike:
    file: lib/Fey/Role/ColumnLike.pm
  Fey::Role::Comparable:
    file: lib/Fey/Role/Comparable.pm
  Fey::Role::Groupable:
    file: lib/Fey/Role/Groupable.pm
  Fey::Role::Joinable:
    file: lib/Fey/Role/Joinable.pm
  Fey::Role::Named:
    file: lib/Fey/Role/Named.pm
  Fey::Role::Orderable:
    file: lib/Fey/Role/Orderable.pm
  Fey::Role::SQL::HasBindParams:
    file: lib/Fey/Role/SQL/HasBindParams.pm
  Fey::Role::SQL::HasLimitClause:
    file: lib/Fey/Role/SQL/HasLimitClause.pm
  Fey::Role::SQL::HasOrderByClause:
    file: lib/Fey/Role/SQL/HasOrderByClause.pm
  Fey::Role::SQL::HasWhereClause:
    file: lib/Fey/Role/SQL/HasWhereClause.pm
  Fey::Role::Selectable:
    file: lib/Fey/Role/Selectable.pm
  Fey::Role::TableLike:
    file: lib/Fey/Role/TableLike.pm
  Fey::SQL:
    file: lib/Fey/SQL.pm
  Fey::SQL::Delete:
    file: lib/Fey/SQL/Delete.pm
  Fey::SQL::Fragment::Join:
    file: lib/Fey/SQL/Fragment/Join.pm
  Fey::SQL::Fragment::SubSelect:
    file: lib/Fey/SQL/Fragment/SubSelect.pm
  Fey::SQL::Fragment::Where::Boolean:
    file: lib/Fey/SQL/Fragment/Where/Boolean.pm
  Fey::SQL::Fragment::Where::Comparison:
    file: lib/Fey/SQL/Fragment/Where/Comparison.pm
  Fey::SQL::Fragment::Where::SubgroupEnd:
    file: lib/Fey/SQL/Fragment/Where/SubgroupEnd.pm
  Fey::SQL::Fragment::Where::SubgroupStart:
    file: lib/Fey/SQL/Fragment/Where/SubgroupStart.pm
  Fey::SQL::Insert:
    file: lib/Fey/SQL/Insert.pm
  Fey::SQL::Select:
    file: lib/Fey/SQL/Select.pm
  Fey::SQL::Update:
    file: lib/Fey/SQL/Update.pm
  Fey::SQL::Where:
    file: lib/Fey/SQL/Where.pm
  Fey::Schema:
    file: lib/Fey/Schema.pm
  Fey::Table:
    file: lib/Fey/Table.pm
  Fey::Table::Alias:
    file: lib/Fey/Table/Alias.pm
  Fey::Types:
    file: lib/Fey/Types.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
